### ISSUE TITLE
Timeout or crash / Memory leaks

### ISSUE THREAD

**Issue by cosad3s** [ChrisTheCoolHut/bcheck#2]
I have used python venv to use bcheck:

```bash
python3 -m venv venv
source venv/bin/activate
pip install -e
```

Then I run a `py-amqp` inside a Docker container, from [https://github.com/celery/py-amqp/blob/main/Dockerfile](https://github.com/celery/py-amqp/blob/main/Dockerfile). Then:

```bash
sudo docker build . -t py-amqp:latest
sudo docker run -p4369:4369 -p5671:5671 -p5672:5672 -p15691:15691 -p15692:15692 -p25672:25672 py-amqp:latest
```

It leads sometimes to the same error from issue https://github.com/ChrisTheCoolHut/bcheck/issues/1:

```bash
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 4/5 [00:20<00:05,  5.71s/it][2023-08-16 14:25:47,486: ERROR/Process-1] Process 'ForkPoolWorker-2' pid:37445 exited with 'signal 9 (SIGKILL)'
[2023-08-16 14:25:48,018: ERROR/Process-1] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 2.')
Traceback (most recent call last):
  File "/xxx/bcheck/venv/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback: 
"""
Traceback (most recent call last):
  File "/xxx/bcheck/venv/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 2.
"""
```

The RAM and SWAP are full (15GB * 2).

... Only if I let the timeout of Celery task by default. If I set `@app.task(time_limit=300)` in `celery_app.py`, I get a timeout.

I run `bcheck` with the example: `bcheck.py -s examples/upload.cgi`

***Edit: attempt with fresh configuration***

Here the full log: 

```bash
❯ bcheck.py -s examples/upload.cgi
[~] examples/upload.cgi
[~] Checking for command injections
[~] Building CFG
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ Elapsed Time: 0:00:00 Time: 0:00:00  
Found 5 test sites in binary
itering
 
 -------------- celery@kali v5.3.1 (emerald-rush)
--- ***** ----- 
-- ******* ---- Linux-6.3.0-kali1-amd64-x86_64-with-glibc2.36 2023-08-16 19:45:52
- *** --- * --- 
- ** ---------- [config]
- ** ---------- .> app:         CeleryTask:0x7f2f7bd82f90
- ** ---------- .> transport:   amqp://guest:**@localhost:5672//
- ** ---------- .> results:     rpc://
- *** --- * --- .> concurrency: 12 (prefork)
-- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
--- ***** ----- 
 -------------- [queues]
                .> celery           exchange=celery(direct) key=celery
                

  0%|                                                                                                                                                                                     | 0/5 [00:00<?, ?it/s][2023-08-16 19:45:53,317: WARNING/Process-1] /opt/bcheck/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

[2023-08-16 19:45:53,320: WARNING/Process-1] /opt/bcheck/venv/lib/python3.11/site-packages/celery/worker/consumer/consumer.py:498: CPendingDeprecationWarning: The broker_connection_retry configuration setting will no longer determine
whether broker connection retries are made during startup in Celery 6.0 and above.
If you wish to retain the existing behavior for retrying connections on startup,
you should set broker_connection_retry_on_startup to True.
  warnings.warn(

 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 4/5 [00:15<00:03,  3.97s/it][2023-08-16 19:46:15,807: ERROR/Process-1] Process 'ForkPoolWorker-1' pid:17964 exited with 'signal 9 (SIGKILL)'
[2023-08-16 19:46:15,912: ERROR/Process-1] Task handler raised error: WorkerLostError('Worker exited prematurely: signal 9 (SIGKILL) Job: 2.')
Traceback (most recent call last):
  File "/opt/bcheck/venv/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.einfo.ExceptionWithTraceback: 
"""
Traceback (most recent call last):
  File "/opt/bcheck/venv/lib/python3.11/site-packages/billiard/pool.py", line 1264, in mark_as_worker_lost
    raise WorkerLostError(
billiard.exceptions.WorkerLostError: Worker exited prematurely: signal 9 (SIGKILL) Job: 2.
"""
 80%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                                  | 4/5 [00:24<00:06,  6.04s/it]
[-] Scanned functions:
[-] : 0x401a28 : getLanIP
[+] : 0x4012b8 : mtd_write_firmware
0x7ffefdf8	->	b'/bin/mtd_write -o 0 -l 0 write AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\x00 Kernel'
[-] : 0x4009f0 : main
[+] : 0x4010d0 : write_flash_kernel_version
0x7ffefdf8	->	b'nvram_set 2860 old_firmware "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\x01"'
[+] : 0x401338 : mtd_write_bootloader
0x7ffefdf8	->	b'/bin/mtd_write -o 0 -l 0 write AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA\x00 Bootloader'
[2023-08-16 19:46:16,855: WARNING/Process-1] Got shutdown from remote
```

**Comment by ChrisTheCoolHut** [comment]
The SIGKILLs are the main process killing those workers that  run longer than your set timeout. This is expected behavior. It looks like it found all the command injections in the example
